export const COMMENT_LIST_BY_POST_REQUEST = 'COMMENT_LIST_BY_POST_REQUEST';
export const COMMENT_LIST_BY_POST_SUCCESS = 'COMMENT_LIST_BY_POST_SUCCESS';
export const COMMENT_LIST_BY_POST_FAIL = 'COMMENT_LIST_BY_POST_FAIL';
export const COMMENT_LIST_BY_POST_RESET = 'COMMENT_LIST_BY_POST_RESET';

export const COMMENT_CREATE_REQUEST = 'COMMENT_CREATE_REQUEST';
export const COMMENT_CREATE_SUCCESS = 'COMMENT_CREATE_SUCCESS';
export const COMMENT_CREATE_FAIL = 'COMMENT_CREATE_FAIL';
export const COMMENT_CREATE_RESET = 'COMMENT_CREATE_RESET';

export const COMMENT_UPDATE_REQUEST = 'COMMENT_UPDATE_REQUEST';
export const COMMENT_UPDATE_SUCCESS = 'COMMENT_UPDATE_SUCCESS';
export const COMMENT_UPDATE_FAIL = 'COMMENT_UPDATE_FAIL';
export const COMMENT_UPDATE_RESET = 'COMMENT_UPDATE_RESET';

export const COMMENT_DELETE_REQUEST = 'COMMENT_DELETE_REQUEST';
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS';
export const COMMENT_DELETE_FAIL = 'COMMENT_DELETE_FAIL';
export const COMMENT_DELETE_RESET = 'COMMENT_DELETE_RESET';
